---
title: "droughtindex"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rayshader)
library(ncdf4)

# library(raster)
```

open the file and extract data of longitude and latitude for raster
```{r}
nc_dat <- nc_open('20200323_NZDI.nc')
# # Save the print(nc) dump to a text file
# {
#     sink('droughtindex_metadata.txt')
#  print(nc_dat)
#     sink()
# }
# lon <- ncvar_get(nc_dat, "lon")
# lat <- ncvar_get(nc_dat, "lat")


```

extract the data as an array
```{r}
ndvi.array <- ncvar_get(nc_dat) 

nc_close(nc_dat) 


```


<!-- use raster and plot the rastered data -->
<!-- https://rpubs.com/boyerag/297592 -->

<!-- assuming the coordinate reference system is the standard well-known text format, WGS84 system -->
<!-- ```{r} -->
<!-- r <- raster(t(ndvi.array), xmn=min(lon), xmx=max(lon), ymn=min(lat), ymx=max(lat), crs=CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs+ towgs84=0,0,0")) -->
<!-- plot(r) -->
<!-- ``` -->






convert the matrix array into a dataframe

```{r}
nc_df <- ndvi.array %>% reshape2::melt()
# nc_df <- ndvi.array %>% reshape2::melt() %>% na.omit


```


create a ggplot raster image
```{r}
# set colour scale
no_breaks <- 2/0.25

colour_scale <- rep("#F3F3F3", no_breaks)
colour_scale[length(colour_scale)] <- "#D45972"
colour_scale[length(colour_scale) - 1] <- "#F57F6E"
colour_scale[length(colour_scale) - 2] <- "#FDB480"
colour_scale[length(colour_scale) - 3] <- "#FEDD95"
colour_scale[length(colour_scale) - 4] <- "#FFFD7D"



gg_di = ggplot(nc_df, aes(Var2, Var1)) +
  geom_raster(aes(fill=value)) +
  scale_fill_gradientn(colours = colour_scale)
#   theme_void()

```


use rayshader to generate a 3d plot
```{r}
plot_gg(gg_di,multicore=TRUE,width=5,height=5,scale=250,windowsize=c(1400,866),
        zoom = 0.55, phi = 30)
```

need a rgl window open to take snapshots or videos

```{r}
render_snapshot()
render_snapshot(clear = TRUE)
```




```{r}
render_movie("nzdi.mp4", title_text = "Drought Index")
```



