---
title: "droughtindex_timelapse2"
output: html_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rayshader)
library(ncdf4)
library(av)
library(lubridate)
library(magick)
source("functions.R")

no_breaks <- 2/0.25

colour_scale <- rep("#F3F3F3", no_breaks)
colour_scale[length(colour_scale)] <- "#D45972"
colour_scale[length(colour_scale) - 1] <- "#F57F6E"
colour_scale[length(colour_scale) - 2] <- "#FDB480"
colour_scale[length(colour_scale) - 3] <- "#FEDD95"
colour_scale[length(colour_scale) - 4] <- "#FFFD7D"

```


```{r}
nc_files <- list.files(pattern = ".nc$") %>% 
  enframe(name = NULL, value = "file") %>% 
  mutate(fdate = lubridate::ymd(str_extract(file, "[^_]+")))
```

```{r}
nc_files %>% 
  mutate(snapshottaken = map2(file, fdate, create_snapshots))
```


```{r}

png_files <- nc_files %>% 
  mutate(png_files = paste0("timeseries/", fdate, ".png")) %>% 
  select(png_files) %>% 
  pull()
av::av_encode_video(png_files, 'timeseries/nzdi_output.mp4', framerate = 1)
```


